import type { Masjid } from './types'
import { photoForId } from './images'
import { emasjidStream } from './emasjid'

const base = (m: Omit<Masjid, 'cityId' | 'coverImage' | 'gallery' | 'events' | 'announcements' | 'rating' | 'reviewCount'> & {
  coverImage?: string
  gallery?: string[]
  events?: Masjid['events']
  announcements?: string[]
  rating?: number
  reviewCount?: number
}): Masjid => ({
  cityId: 'birmingham',
  coverImage: photoForId(m.id),
  gallery: [],
  events: [],
  announcements: [],
  rating: 4.5,
  reviewCount: 60,
  ...m,
})

export const BIRMINGHAM_MASJIDS: Masjid[] = [
  base({
    id: 'm5',
    slug: 'birmingham-central-mosque',
    name: 'Birmingham Central Mosque',
    address: '180 Belgrave Middleway',
    postcode: 'B12 0XS',
    lat: 52.4623,
    lng: -1.8845,
    phone: '0121 440 5355',
    email: 'info@centralmosque.org.uk',
    website: 'https://centralmosque.org.uk',
    facebook: 'https://www.facebook.com/BirminghamCentralMosque',
    youtube: 'https://www.youtube.com/@Bhamcentralmosque',
    description: 'Birmingham Central Mosque on Belgrave Middleway — iconic masjid with golden dome and BCM Radio.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'food-bank', 'counselling', 'parking', 'disabled-access'],
    liveStream: {
      platform: 'website',
      url: 'https://centralmosque.org.uk/bcm-radio-station',
      pageUrl: 'https://centralmosque.org.uk/',
      isLive: false,
      alwaysOn: true,
      title: 'BCM Radio — Birmingham Central Mosque',
    },
    announcements: ['One Jumu\'ah salah only. Ladies facilities on 2nd floor.'],
    parkingInfo: 'Parking at masjid car park on Belgrave Middleway.',
    rating: 4.6,
    reviewCount: 456,
    featured: true,
  }),
  base({
    id: 'b1',
    slug: 'birmingham-jame-masjid',
    name: 'Birmingham Jame Masjid',
    address: '2 Trinity Road, Aston',
    postcode: 'B6 6AG',
    lat: 52.5083,
    lng: -1.9029,
    phone: '0121 554 9157',
    email: 'enquiry@birminghamjamemasjid.org.uk',
    website: 'https://birminghamjamemasjid.org.uk',
    facebook: 'https://www.facebook.com/BirminghamJameMasjid',
    emasjidSlug: 'birminghamjamemasjid',
    description: 'Birmingham Jame Masjid on Trinity Road in Aston — major community masjid with daily salah and madrasah.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'youth-club', 'disabled-access'],
    liveStream: emasjidStream('birminghamjamemasjid', 'Birmingham Jame Masjid — eMasjid Live'),
    featured: true,
    rating: 4.7,
    reviewCount: 188,
  }),
  base({
    id: 'b2',
    slug: 'al-habib-trust-birmingham',
    name: 'Al-Habib Trust',
    address: '101 Birchfield Road, Aston',
    postcode: 'B19 1LH',
    lat: 52.4982,
    lng: -1.8864,
    website: 'https://alhabib.co.uk',
    emasjidSlug: 'alhabib',
    description: 'Al-Habib Trust in Aston — Islamic centre serving Birmingham with education and community programmes.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling', 'youth-club', 'womens-programme'],
    liveStream: emasjidStream('alhabib', 'Al-Habib Trust — eMasjid Live'),
    featured: true,
    rating: 4.6,
    reviewCount: 92,
  }),
  base({
    id: 'b3',
    slug: 'kings-heath-masjid',
    name: 'Kings Heath Masjid',
    address: '113–115 Station Road, Kings Heath',
    postcode: 'B14 7TA',
    lat: 52.4354,
    lng: -1.8942,
    emasjidSlug: 'kingsheathmasjid',
    description: 'Kings Heath Masjid on Station Road — central masjid for south Birmingham Muslims.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah', 'funeral', 'parking'],
    liveStream: emasjidStream('kingsheathmasjid', 'Kings Heath Masjid — eMasjid Live'),
    rating: 4.5,
    reviewCount: 74,
  }),
  base({
    id: 'b4',
    slug: 'masjid-naqeebul-islam-saltley',
    name: 'Masjid Naqeebul Islam',
    address: '78–82 Washwood Heath Road, Saltley',
    postcode: 'B8 1RD',
    lat: 52.4965,
    lng: -1.8441,
    phone: '0121 328 4930',
    emasjidSlug: 'masjidnaqeebulislam',
    description: 'Masjid Naqeebul Islam on Washwood Heath Road in Saltley — established local masjid with eMasjid Live.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah'],
    liveStream: emasjidStream('masjidnaqeebulislam', 'Masjid Naqeebul Islam — eMasjid Live'),
    rating: 4.5,
    reviewCount: 68,
  }),
  base({
    id: 'b5',
    slug: 'masjid-ul-madni-birmingham',
    name: 'Masjid Ul Madni',
    address: '58 Trinity Road, Aston',
    postcode: 'B6 6NH',
    lat: 52.5084,
    lng: -1.9008,
    phone: '0121 551 1239',
    website: 'https://madnimasjid.com',
    emasjidSlug: 'masjidulmadni',
    description: 'Masjid Ul Madni on Trinity Road in Aston — community masjid with official eMasjid Live stream.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'food-bank'],
    liveStream: emasjidStream('masjidulmadni', 'Masjid Ul Madni — eMasjid Live'),
    rating: 4.6,
    reviewCount: 81,
  }),
  base({
    id: 'b6',
    slug: 'masjid-yousuf-sheldon',
    name: 'Masjid Yousuf',
    address: '84 Sheldon Heath Road, Sheldon',
    postcode: 'B26 2TU',
    lat: 52.4541,
    lng: -1.7818,
    emasjidSlug: 'masjidyousufsheldon',
    description: 'Masjid Yousuf in Sheldon — local masjid serving east Birmingham with eMasjid Live audio.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah', 'funeral'],
    liveStream: emasjidStream('masjidyousufsheldon', 'Masjid Yousuf — eMasjid Live'),
    rating: 4.4,
    reviewCount: 55,
  }),
  base({
    id: 'b7',
    slug: 'jami-mosque-birmingham',
    name: 'Jami Mosque & Islamic Centre',
    address: '521–527 Coventry Road, Small Heath',
    postcode: 'B10 0LL',
    lat: 52.4684,
    lng: -1.8560,
    phone: '0121 772 6408',
    email: 'jami_mosque@yahoo.co.uk',
    website: 'https://www.jamimosque.org.uk',
    emasjidSlug: 'jamimosque',
    description: 'Jami Mosque on Coventry Road in Small Heath — one of Birmingham\'s longstanding Islamic centres.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'counselling', 'disabled-access'],
    liveStream: emasjidStream('jamimosque', 'Jami Mosque — eMasjid Live'),
    rating: 4.5,
    reviewCount: 102,
  }),
  base({
    id: 'b8',
    slug: 'green-oak-academy-birmingham',
    name: 'Green Oak Academy',
    address: 'Greenwood Road, Kings Heath',
    postcode: 'B14 7AJ',
    lat: 52.4288,
    lng: -1.8895,
    emasjidSlug: 'goa',
    description: 'Green Oak Academy masjid and education centre in Kings Heath.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club', 'womens-programme'],
    liveStream: emasjidStream('goa', 'Green Oak Academy — eMasjid Live'),
    rating: 4.5,
    reviewCount: 48,
  }),
]
