import type { Masjid } from './types'
import { photoForId } from './images'
import { emasjidStream } from './emasjid'

const base = (m: Omit<Masjid, 'cityId' | 'coverImage' | 'gallery' | 'events' | 'announcements' | 'rating' | 'reviewCount'> & {
  coverImage?: string
  gallery?: string[]
  events?: Masjid['events']
  announcements?: string[]
  rating?: number
  reviewCount?: number
}): Masjid => ({
  cityId: 'dewsbury',
  coverImage: photoForId(m.id),
  gallery: [],
  events: [],
  announcements: [],
  rating: 4.5,
  reviewCount: 60,
  ...m,
})

export const DEWSBURY_MASJIDS: Masjid[] = [
  base({
    id: 'd1',
    slug: 'markazi-masjid-dewsbury',
    name: 'Markazi Masjid (Dewsbury)',
    address: 'South Street, Savile Town',
    postcode: 'WF12 9NG',
    lat: 53.6891,
    lng: -1.6412,
    phone: '01924 464 700',
    description: 'Markazi Masjid (Anjuman-e-Islahul Muslimeen) in Savile Town is one of the largest purpose-built masjids in Europe, seating up to 4,000 worshippers.',
    history: 'Historic Tablighi Jamaat centre and Islamic seminary, founded in 1980.',
    jumuahTimes: ['14:00'],
    services: ['madrasah', 'funeral', 'nikah'],
    rating: 4.6,
    reviewCount: 120,
    featured: true,
  }),
  base({
    id: 'd2',
    slug: 'darul-ilm-dewsbury',
    name: 'Darul Ilm (Thornhill Lees Central Mosque)',
    address: '22 Brewery Lane, Thornhill Lees',
    postcode: 'WF12 9HU',
    lat: 53.6865,
    lng: -1.6280,
    phone: '01924 734795',
    website: 'https://darulilm.org.uk',
    emasjidSlug: 'darulilmdewsbury',
    description: 'Darul Ilm on Brewery Lane — central masjid and Islamic centre serving Thornhill Lees with daily salah and community programmes.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'food-bank', 'youth-club', 'counselling'],
    liveStream: emasjidStream('darulilmdewsbury', 'Darul Ilm — eMasjid Live'),
    featured: true,
    rating: 4.8,
    reviewCount: 145,
  }),
  base({
    id: 'd3',
    slug: 'zakaria-masjid-dewsbury',
    name: 'Zakaria Masjid',
    address: '2 Chapel Street, Savile Town',
    postcode: 'WF12 9NQ',
    lat: 53.6885,
    lng: -1.6395,
    website: 'https://www.zakaria.org.uk',
    emasjidSlug: 'zakariamasjid',
    description: 'Zakaria Masjid on Chapel Street in Savile Town — established community masjid with education centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah'],
    liveStream: emasjidStream('zakariamasjid', 'Zakaria Masjid — eMasjid Live'),
    rating: 4.7,
    reviewCount: 98,
    featured: true,
  }),
  base({
    id: 'd4',
    slug: 'masjid-e-umar-dewsbury',
    name: 'Masjid-e-Umar (North View Mosque)',
    address: 'North View, Savile Town',
    postcode: 'WF12 9LF',
    lat: 53.6902,
    lng: -1.6380,
    phone: '01924 464 026',
    email: 'info@masjideumar.co.uk',
    website: 'https://masjideumar.co.uk',
    emasjidSlug: 'meudewsbury',
    description: 'Masjid-e-Umar on North View in Savile Town — local receiver 454.050 MHz, also on eMasjid Live.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'food-bank'],
    liveStream: emasjidStream('meudewsbury', 'Masjid-e-Umar — eMasjid Live'),
    rating: 4.6,
    reviewCount: 87,
  }),
  base({
    id: 'd5',
    slug: 'masjid-ur-rahman-dewsbury',
    name: 'Masjid Ur Rahman',
    address: '6 Hartley Street',
    postcode: 'WF13 2BJ',
    lat: 53.6920,
    lng: -1.6350,
    emasjidSlug: 'masjidurrahman',
    description: 'Masjid Ur Rahman on Hartley Street serving the Dewsbury community.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral'],
    liveStream: emasjidStream('masjidurrahman', 'Masjid Ur Rahman — eMasjid Live'),
    rating: 4.5,
    reviewCount: 72,
  }),
  base({
    id: 'd6',
    slug: 'masjid-talha-dewsbury',
    name: 'Masjid Talha',
    address: 'Nowell Street',
    postcode: 'WF13 4JT',
    lat: 53.6840,
    lng: -1.6520,
    emasjidSlug: 'talha',
    description: 'Masjid Talha on Nowell Street — community masjid in Dewsbury.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('talha', 'Masjid Talha — eMasjid Live'),
    rating: 4.5,
    reviewCount: 65,
  }),
  base({
    id: 'd7',
    slug: 'madrasah-al-hira-dewsbury',
    name: 'Madrasah Al Hira (Staincliffe)',
    address: '2 William Street, Staincliffe',
    postcode: 'WF13 4AY',
    lat: 53.6810,
    lng: -1.6480,
    phone: '07974 283663',
    emasjidSlug: 'alhira',
    description: 'Madrasah Al Hira on William Street in Staincliffe — masjid and madrasah.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('alhira', 'Madrasah Al Hira — eMasjid Live'),
    rating: 4.9,
    reviewCount: 21,
  }),
  base({
    id: 'd8',
    slug: 'madni-jamia-masjid-dewsbury',
    name: 'Madni Jamia Masjid (Dewsbury Town Centre)',
    address: '2 Bradford Road',
    postcode: 'WF13 1DZ',
    lat: 53.6915,
    lng: -1.6310,
    emasjidSlug: 'madnimasjiddewsburytown',
    description: 'Madni Jamia Masjid in Dewsbury town centre on Bradford Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah'],
    liveStream: emasjidStream('madnimasjiddewsburytown', 'Madni Jamia Masjid — eMasjid Live'),
    rating: 4.5,
    reviewCount: 80,
  }),
  base({
    id: 'd9',
    slug: 'islamic-tarbiyah-academy-dewsbury',
    name: 'Islamic Tarbiyah Academy',
    address: '45 Boothroyd Lane, Westtown',
    postcode: 'WF13 2RB',
    lat: 53.6950,
    lng: -1.6450,
    phone: '01924 450422',
    email: 'info@islamictarbiyah.com',
    website: 'https://islamictarbiyah.com',
    emasjidSlug: 'ita',
    description: 'Islamic Tarbiyah Academy on Boothroyd Lane — masjid, madrasah, and community guidance centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    liveStream: emasjidStream('ita', 'Islamic Tarbiyah Academy — eMasjid Live'),
    rating: 4.7,
    reviewCount: 110,
  }),
  base({
    id: 'd10',
    slug: 'masjid-e-bilal-dewsbury',
    name: 'Masjid E Bilal',
    address: 'Parker Road, Thornhill Lees',
    postcode: 'WF12 0AR',
    lat: 53.6855,
    lng: -1.6250,
    website: 'https://masjidebilal.org.uk',
    emasjidSlug: 'masjidbilaldewsbury',
    description: 'Masjid E Bilal on Parker Road in Thornhill Lees.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah'],
    liveStream: emasjidStream('masjidbilaldewsbury', 'Masjid E Bilal — eMasjid Live'),
    rating: 4.5,
    reviewCount: 58,
  }),
  base({
    id: 'd11',
    slug: 'masjid-heera-dewsbury',
    name: 'Masjid E Hira (Thornhill Lees)',
    address: 'Thornhill Road, Thornhill Lees',
    postcode: 'WF12 9BX',
    lat: 53.6870,
    lng: -1.6265,
    emasjidSlug: 'masjidheera',
    description: 'Masjid E Hira on Thornhill Road — also home to the Islamic Research Institute.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    liveStream: emasjidStream('masjidheera', 'Masjid E Hira — eMasjid Live'),
    rating: 4.4,
    reviewCount: 52,
  }),
  base({
    id: 'd12',
    slug: 'masjid-noor-dewsbury',
    name: 'Masjid Noor & Education Centre',
    address: 'Lees Hall Road, Thornhill Lees',
    postcode: 'WF12 9ER',
    lat: 53.6860,
    lng: -1.6240,
    emasjidSlug: 'masjidnoordewsbury',
    description: 'Masjid Noor and Education Centre on Lees Hall Road in Thornhill Lees.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    liveStream: emasjidStream('masjidnoordewsbury', 'Masjid Noor — eMasjid Live'),
    rating: 4.4,
    reviewCount: 48,
  }),
  base({
    id: 'd13',
    slug: 'masjid-bait-ut-tauheed-dewsbury',
    name: 'Masjid Bait-Ut-Tauheed',
    address: 'Ravensthorpe Road, Ravensthorpe',
    postcode: 'WF13 3EE',
    lat: 53.6750,
    lng: -1.6580,
    emasjidSlug: 'masjidbaituttauheed',
    description: 'Masjid Bait-Ut-Tauheed on Ravensthorpe Road serving the Ravensthorpe area of Dewsbury.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('masjidbaituttauheed', 'Masjid Bait-Ut-Tauheed — eMasjid Live'),
    rating: 4.4,
    reviewCount: 44,
  }),
  base({
    id: 'd14',
    slug: 'masjid-as-salaam-dewsbury',
    name: 'Masjid As-Salaam (Earlsheaton)',
    address: 'Earlsheaton',
    postcode: 'WF12 8DJ',
    lat: 53.6980,
    lng: -1.6120,
    emasjidSlug: 'masjidassalaam',
    description: 'Masjid As-Salaam serving the Earlsheaton area of Dewsbury.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('masjidassalaam', 'Masjid As-Salaam — eMasjid Live'),
    rating: 4.3,
    reviewCount: 40,
  }),
  base({
    id: 'd15',
    slug: 'ilaahi-masjid-dewsbury',
    name: 'Ilaahi Masjid',
    address: 'Hope Street',
    postcode: 'WF13 2AL',
    lat: 53.6935,
    lng: -1.6385,
    emasjidSlug: 'ilaahi',
    description: 'Ilaahi Masjid on Hope Street in Dewsbury.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('ilaahi', 'Ilaahi Masjid — eMasjid Live'),
    rating: 4.4,
    reviewCount: 46,
  }),
  base({
    id: 'd16',
    slug: 'upper-soothill-islamic-centre',
    name: 'Upper Soothill Islamic Centre',
    address: 'Upper Soothill, Batley',
    postcode: 'WF17 6BP',
    lat: 53.7020,
    lng: -1.6180,
    emasjidSlug: 'usic',
    description: 'Upper Soothill Islamic Centre serving the Soothill and Batley border community.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'food-bank'],
    liveStream: emasjidStream('usic', 'Upper Soothill Islamic Centre — eMasjid Live'),
    rating: 4.5,
    reviewCount: 55,
  }),
  base({
    id: 'd17',
    slug: 'madina-academy-dewsbury',
    name: 'Madina Academy',
    address: 'Dewsbury',
    postcode: 'WF13 1HD',
    lat: 53.6900,
    lng: -1.6330,
    emasjidSlug: 'madina_academy',
    description: 'Madina Academy madrasah and masjid facilities in Dewsbury.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: emasjidStream('madina_academy', 'Madina Academy — eMasjid Live'),
    rating: 4.3,
    reviewCount: 38,
  }),
]
