import type { Masjid } from './types'
import { photoForId } from './images'
import { emasjidStream } from './emasjid'

const centralAudio = {
  platform: 'audio' as const,
  url: 'https://stream.zeno.fm/jnovbt6co2ktv',
  pageUrl: 'https://www.islamiccentre.org/2-uncategorised/1494-live-audio-streaming',
  isLive: false,
  alwaysOn: true,
  title: 'Leicester Islamic Centre — Live Audio',
}

const base = (m: Omit<Masjid, 'cityId' | 'coverImage' | 'gallery' | 'events' | 'announcements' | 'rating' | 'reviewCount'> & {
  coverImage?: string
  gallery?: string[]
  events?: Masjid['events']
  announcements?: string[]
  rating?: number
  reviewCount?: number
}): Masjid => ({
  cityId: 'leicester',
  coverImage: photoForId(m.id),
  gallery: [],
  events: [],
  announcements: [],
  rating: 4.5,
  reviewCount: 50,
  ...m,
})

const ej = (slug: string, title: string) => emasjidStream(slug, title)

export const LEICESTER_MASJIDS: Masjid[] = [
  // ── eMasjid Live + major masjids ──────────────────────────────────────────
  base({
    id: 'm1',
    slug: 'leicester-central-masjid',
    name: 'Leicester Central Mosque (Islamic Centre)',
    address: '1 Conduit Street',
    postcode: 'LE2 0JN',
    lat: 52.6312,
    lng: -1.1227,
    phone: '0116 254 4459',
    email: 'info@islamiccentre.org',
    website: 'https://www.islamiccentre.org',
    facebook: 'https://www.facebook.com/LeicesterIslamicCentre',
    youtube: 'https://www.youtube.com/user/wwwIslamicCentreOrg',
    description: 'The Leicester Central Mosque at the Islamic Centre on Conduit Street is one of the city\'s principal masjids.',
    history: 'The Islamic Centre Leicester has served the Muslim community since the 1970s.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'food-bank', 'youth-club', 'womens-facilities', 'disabled-access', 'parking'],
    liveStream: { ...centralAudio, title: 'Leicester Central Mosque — Live Audio' },
    announcements: ['Second Jumu\'ah at Leicester Mosque (Sutherland St) during summer — see website.'],
    parkingInfo: 'Limited parking on Conduit Street.',
    rating: 4.7,
    reviewCount: 128,
    featured: true,
  }),
  base({
    id: 'l26',
    slug: 'leicester-mosque-sutherland-street',
    name: 'Leicester Mosque & Islamic Centre (Sutherland Street)',
    address: '2a Sutherland Street',
    postcode: 'LE2 1DS',
    lat: 52.6293,
    lng: -1.1126,
    phone: '0116 285 4052',
    website: 'https://www.islamiccentre.org',
    description: 'Second masjid of the Leicester Islamic Centre on Sutherland Street — summer Jumu\'ah and daily salah.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'disabled-access'],
    liveStream: centralAudio,
    rating: 4.6,
    reviewCount: 75,
  }),
  base({
    id: 'm3',
    slug: 'jame-masjid-leicester',
    name: 'Jame Masjid & Islamic Centre',
    address: '51 Asfordby Street',
    postcode: 'LE5 3QJ',
    lat: 52.6472,
    lng: -1.0894,
    phone: '0116 251 8606',
    website: 'https://jamemasjid.co.uk',
    emasjidSlug: 'jamemasjid',
    description: 'Jame Masjid on Asfordby Street — major Islamic centre with madrasah, darul uloom, and community facilities.',
    jumuahTimes: ['13:00'],
    services: ['madrasah', 'funeral', 'nikah', 'counselling', 'youth-club', 'disabled-access'],
    liveStream: ej('jamemasjid', 'Jame Masjid — eMasjid Live'),
    rating: 4.8,
    reviewCount: 210,
    featured: true,
  }),
  base({
    id: 'm9',
    slug: 'peace-centre-leicester',
    name: 'As-Salaam Trust — The Peace Centre',
    address: '198 Thurncourt Road, Thurnby Lodge',
    postcode: 'LE5 2NG',
    lat: 52.6365,
    lng: -1.0750,
    phone: '0116 241 7100',
    email: 'info@peacecentre.org.uk',
    website: 'https://peacecentre.org.uk',
    emasjidSlug: 'peacecentre',
    description: 'The Peace Centre on Thurncourt Road provides masjid facilities, education, and a community food bank.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'food-bank', 'youth-club', 'womens-programme', 'parking'],
    liveStream: ej('peacecentre', 'The Peace Centre — eMasjid Live'),
    featured: true,
    rating: 4.6,
    reviewCount: 95,
  }),
  base({
    id: 'm10',
    slug: 'darul-arqam-leicester',
    name: 'Darul Arqam Educational Trust',
    address: '16 Thurmaston Lane',
    postcode: 'LE5 0TE',
    lat: 52.6484,
    lng: -1.0816,
    phone: '0116 319 1984',
    email: 'info@datrust.org',
    website: 'https://datrust.org',
    emasjidSlug: 'darularqameducationaltrust',
    description: 'Darul Arqam Educational Trust on Thurmaston Lane — masjid and Islamic education centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling', 'youth-club'],
    liveStream: ej('darularqameducationaltrust', 'Darul Arqam — eMasjid Live'),
    rating: 4.5,
    reviewCount: 62,
  }),
  base({
    id: 'm11',
    slug: 'madani-masjid-leicester',
    name: 'Madani Masjid (Madani School)',
    address: '77 Evington Valley Road',
    postcode: 'LE5 5LL',
    lat: 52.6190,
    lng: -1.0920,
    phone: '0116 249 8080',
    website: 'https://madani.school',
    emasjidSlug: 'madanimasjid',
    description: 'Madani Masjid on Evington Valley Road serves the Evington community with daily prayers and madrasah.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    liveStream: ej('madanimasjid', 'Madani Masjid — eMasjid Live'),
    rating: 4.5,
    reviewCount: 74,
  }),
  base({
    id: 'm12',
    slug: 'knighton-masjid-leicester',
    name: 'Madrasah Ta\'leemul Qur\'an (Knighton CEC)',
    address: 'Rear of 252–258 Knighton Lane East',
    postcode: 'LE2 6FU',
    lat: 52.6120,
    lng: -1.0980,
    website: 'https://masjid-us-sunnah.com',
    emasjidSlug: 'knightonmasjid',
    description: 'Knighton Community & Education Centre — daily salah and Islamic education on Knighton Lane East.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: ej('knightonmasjid', 'Knighton Masjid — eMasjid Live'),
    rating: 4.4,
    reviewCount: 48,
  }),
  base({
    id: 'm13',
    slug: 'masjid-abu-hurairah-leicester',
    name: 'Masjid Abu Hurairah',
    address: '9 Haynes Road',
    postcode: 'LE5 4AR',
    lat: 52.6380,
    lng: -1.0850,
    phone: '07513 638296',
    email: 'admin@madrasahabuhurairah.co.uk',
    website: 'https://madrasahabuhurairah.co.uk',
    emasjidSlug: 'abuhurairah',
    description: 'Masjid Abu Hurairah on Haynes Road with attached madrasah serving the local community.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: ej('abuhurairah', 'Masjid Abu Hurairah — eMasjid Live'),
    rating: 4.6,
    reviewCount: 55,
  }),
  base({
    id: 'm14',
    slug: 'masjid-adam-oadby',
    name: 'Masjid Adam (A.S), Oadby',
    address: '46 Adlington Road, Oadby',
    postcode: 'LE2 4FY',
    lat: 52.6010,
    lng: -1.0780,
    emasjidSlug: 'masjidadamoadby',
    description: 'Masjid Adam in Oadby serving the south Leicester Muslim community.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah'],
    liveStream: ej('masjidadamoadby', 'Masjid Adam Oadby — eMasjid Live'),
    rating: 4.5,
    reviewCount: 41,
  }),
  base({
    id: 'm15',
    slug: 'masjid-al-furqan-leicester',
    name: 'Masjid Al Furqan',
    address: '298 East Park Road',
    postcode: 'LE5 5AY',
    lat: 52.6314,
    lng: -1.1061,
    phone: '0116 273 5799',
    website: 'https://madrasahalfurqan.co.uk',
    emasjidSlug: 'masjidalfurqan',
    description: 'Masjid Al Furqan on East Park Road — community masjid in the St Matthew\'s area.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'food-bank'],
    liveStream: ej('masjidalfurqan', 'Masjid Al Furqan — eMasjid Live'),
    rating: 4.5,
    reviewCount: 67,
  }),
  base({
    id: 'm16',
    slug: 'masjid-abdullah-ibn-masud',
    name: 'Masjid e Abdullah Ibn Mas\'ud (RA)',
    address: '20 Hallaton Street',
    postcode: 'LE2 8QU',
    lat: 52.6080,
    lng: -1.1150,
    emasjidSlug: 'abdullahibnmasud',
    description: 'Masjid e Abdullah Ibn Mas\'ud on Hallaton Street in the Highfields area.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    liveStream: ej('abdullahibnmasud', 'Masjid e Abdullah Ibn Mas\'ud — eMasjid Live'),
    rating: 4.4,
    reviewCount: 38,
  }),
  base({
    id: 'm17',
    slug: 'masjid-muadh-ibn-jabal',
    name: 'Masjid Muadh Ibn Jabal',
    address: '60 Gamel Road, Rowlatts Hill',
    postcode: 'LE5 6TB',
    lat: 52.6450,
    lng: -1.0650,
    phone: '07903 046525',
    website: 'https://www.muadhibnjabal.org',
    emasjidSlug: 'muadhibnjabal',
    description: 'Masjid Muadh Ibn Jabal on Gamel Road serving Rowlatts Hill and surrounding areas.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    liveStream: ej('muadhibnjabal', 'Masjid Muadh Ibn Jabal — eMasjid Live'),
    rating: 4.5,
    reviewCount: 52,
  }),
  base({
    id: 'm18',
    slug: 'masjid-muhammad-leicester',
    name: 'Masjid Muhammad',
    address: '5 Claymill Road, Thurmaston',
    postcode: 'LE4 9JJ',
    lat: 52.6780,
    lng: -1.0950,
    emasjidSlug: 'masjidmuhammad',
    description: 'Masjid Muhammad on Claymill Road in Thurmaston, north Leicester.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah'],
    liveStream: ej('masjidmuhammad', 'Masjid Muhammad — eMasjid Live'),
    rating: 4.6,
    reviewCount: 88,
  }),
  base({
    id: 'm19',
    slug: 'masjid-imam-bukhari-leicester',
    name: 'Masjid-ul-Imam-il-Bukhari',
    address: '159 Loughborough Road, Belgrave',
    postcode: 'LE4 5LR',
    lat: 52.6511,
    lng: -1.1317,
    phone: '0116 266 6688',
    email: 'info@madrasahimambukhari.com',
    website: 'https://madrasahimambukhari.com',
    emasjidSlug: 'bukhari',
    description: 'Masjid-ul-Imam-il-Bukhari on Loughborough Road in Belgrave.',
    jumuahTimes: ['13:00'],
    services: ['madrasah', 'counselling'],
    liveStream: ej('bukhari', 'Masjid-ul-Imam-il-Bukhari — eMasjid Live'),
    rating: 4.7,
    reviewCount: 76,
    featured: true,
  }),
  base({
    id: 'm21',
    slug: 'masjid-aisha-leicester',
    name: 'Masjid Aisha',
    address: '22–28 Cork Street',
    postcode: 'LE5 5AN',
    lat: 52.6309,
    lng: -1.1098,
    phone: '0116 212 4883',
    website: 'https://masjidaisha.co.uk',
    emasjidSlug: 'masjidaisha',
    description: 'Masjid Aisha on Cork Street serving the St Matthew\'s community.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'womens-programme'],
    liveStream: ej('masjidaisha', 'Masjid Aisha — eMasjid Live'),
    rating: 4.4,
    reviewCount: 44,
  }),
  base({
    id: 'l27',
    slug: 'al-ehsaan-academy-leicester',
    name: 'Al Ehsaan Academy',
    address: '92–96 Evington Road',
    postcode: 'LE2 1HH',
    lat: 52.6215,
    lng: -1.1080,
    phone: '0116 254 7572',
    email: 'Info@alehsaanacademy.org',
    website: 'https://alehsaanacademy.org',
    emasjidSlug: 'alehsaanacademy',
    description: 'Al Ehsaan Academy on Evington Road — masjid, madrasah, and community centre established 2018.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club', 'womens-programme', 'food-bank'],
    liveStream: ej('alehsaanacademy', 'Al Ehsaan Academy — eMasjid Live'),
    rating: 4.5,
    reviewCount: 58,
  }),
  base({
    id: 'l28',
    slug: 'darul-ihsaan-leicester',
    name: 'Darul Ihsaan (The Mayflower)',
    address: '1 Gervas Road',
    postcode: 'LE5 2EH',
    lat: 52.6345,
    lng: -1.0680,
    emasjidSlug: 'darulihsaan',
    description: 'Darul Ihsaan community centre and masjid on Gervas Road in Thurnby Lodge.',
    jumuahTimes: ['13:00'],
    services: ['madrasah', 'counselling'],
    liveStream: ej('darulihsaan', 'Darul Ihsaan — eMasjid Live'),
    rating: 4.4,
    reviewCount: 40,
  }),
  base({
    id: 'l29',
    slug: 'al-qalam-institute-leicester',
    name: 'Al-Qalam Institute',
    address: '6 Sylvan Avenue, North Evington',
    postcode: 'LE5 3SN',
    lat: 52.6210,
    lng: -1.0773,
    website: 'https://www.alqalaminstitute.org',
    emasjidSlug: 'alqalaminstitute',
    description: 'Al-Qalam Institute on Sylvan Avenue — Islamic education and masjid facilities.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    liveStream: ej('alqalaminstitute', 'Al-Qalam Institute — eMasjid Live'),
    rating: 4.4,
    reviewCount: 35,
  }),
  base({
    id: 'l30',
    slug: 'as-safwah-institute-leicester',
    name: 'As-Safwah Institute',
    address: '342 St Saviours Road',
    postcode: 'LE5 4HJ',
    lat: 52.6388,
    lng: -1.1092,
    website: 'https://assafwahinstitute.org',
    emasjidSlug: 'assafwah',
    description: 'As-Safwah Institute on St Saviours Road — education, events, and masjid salah.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club', 'womens-programme'],
    liveStream: ej('assafwah', 'As-Safwah Institute — eMasjid Live'),
    rating: 4.4,
    reviewCount: 32,
  }),
  base({
    id: 'l31',
    slug: 'baytul-ihsaan-hamilton',
    name: 'Darul Fath Hamilton Trust — Baytul Ihsaan',
    address: '202 Sandhills Avenue, Hamilton',
    postcode: 'LE5 1PL',
    lat: 52.6490,
    lng: -1.0620,
    website: 'https://dfhtrust.org',
    emasjidSlug: 'darulfathhamiltontrust_bi',
    description: 'Baytul Ihsaan masjid and community hub operated by Darul Fath Hamilton Trust.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'food-bank', 'womens-programme'],
    liveStream: ej('darulfathhamiltontrust_bi', 'Baytul Ihsaan — eMasjid Live'),
    rating: 4.5,
    reviewCount: 45,
  }),
  base({
    id: 'l32',
    slug: 'hamilton-hub-leicester',
    name: 'Darul Fath Hamilton Trust — The Hamilton Hub',
    address: 'Unit 1, Maidenwell Avenue, Hamilton',
    postcode: 'LE5 1BJ',
    lat: 52.6510,
    lng: -1.0580,
    phone: '07849 806013',
    email: 'contact@dfhtrust.org',
    website: 'https://dfhtrust.org',
    emasjidSlug: 'darulfathhamiltontrust_hh',
    description: 'The Hamilton Hub — masjid, food bank, and community services in Hamilton, Leicester.',
    jumuahTimes: ['13:00'],
    services: ['madrasah', 'food-bank', 'counselling'],
    liveStream: ej('darulfathhamiltontrust_hh', 'The Hamilton Hub — eMasjid Live'),
    rating: 4.5,
    reviewCount: 48,
  }),

  // ── Other Leicester masjids (address; stream where available) ────────────
  base({
    id: 'm20',
    slug: 'masjid-umar-leicester',
    name: 'Masjid Umar (Evington Muslim Centre)',
    address: '5–7 Evington Drive',
    postcode: 'LE5 5PF',
    lat: 52.6185,
    lng: -1.0780,
    phone: '0116 273 5529',
    email: 'info@masjid-umar.org',
    website: 'https://masjid-umar.org',
    description: 'Masjid Umar (Evington Muslim Centre) on Evington Drive — one of Leicester\'s established masjids.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah', 'youth-club'],
    rating: 4.7,
    reviewCount: 102,
    featured: true,
  }),
  base({
    id: 'm2',
    slug: 'usmani-mosque-leicester',
    name: 'Usmani Mosque',
    address: '308 St Saviours Road',
    postcode: 'LE5 4HJ',
    lat: 52.6384,
    lng: -1.1098,
    phone: '07875 043391',
    email: 'info@usmanimosque.com',
    website: 'https://usmanimosque.com',
    description: 'Usmani Mosque on St Saviours Road serves Highfields with daily salah, madrasah, and nikah services.',
    jumuahTimes: ['13:30', '16:00'],
    services: ['madrasah', 'nikah', 'funeral', 'food-bank', 'womens-programme', 'parking'],
    parkingInfo: 'Street parking on St Saviours Road.',
    rating: 4.8,
    reviewCount: 83,
    featured: true,
  }),
  base({
    id: 'm22',
    slug: 'masjid-usman-leicester',
    name: 'Masjid e Usman',
    address: '162 Nedham Street',
    postcode: 'LE2 0HB',
    lat: 52.6344,
    lng: -1.1272,
    phone: '0116 262 1059',
    description: 'Masjid e Usman on Nedham Street near the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 36,
  }),
  base({
    id: 'm23',
    slug: 'masjid-an-noor-leicester',
    name: 'Masjid An Noor',
    address: '170a Belgrave Gate',
    postcode: 'LE1 3XL',
    lat: 52.6342,
    lng: -1.1102,
    phone: '0116 251 9952',
    email: 'madrasatulnoor.01@gmail.com',
    website: 'https://madrassatulnoor.org',
    description: 'Masjid An Noor on Belgrave Gate in the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 58,
  }),
  base({
    id: 'm24',
    slug: 'masjid-at-taqwa-leicester',
    name: 'Masjid at-Taqwa Islamic Education Centre',
    address: '1 Harewood Street',
    postcode: 'LE5 3LX',
    lat: 52.6408,
    lng: -1.1049,
    phone: '0116 212 5802',
    email: 'mail@attaqwa.co.uk',
    website: 'https://attaqwa.co.uk',
    description: 'Masjid at-Taqwa on Harewood Street — education centre and prayer space.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    rating: 4.5,
    reviewCount: 42,
  }),
  base({
    id: 'm25',
    slug: 'al-furqan-centre-leicester',
    name: 'Al Furqan Centre',
    address: '1 Kamloops Crescent',
    postcode: 'LE1 2HX',
    lat: 52.6408,
    lng: -1.1257,
    phone: '0116 251 7342',
    email: 'info@alfurqancentre.co.uk',
    website: 'https://masjidalfurqan.com',
    description: 'Al Furqan Centre on Kamloops Crescent near the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 31,
  }),
  base({
    id: 'l33',
    slug: 'masjid-quba-leicester',
    name: 'Masjid Quba',
    address: '19 Brunswick Street / 08 Madras Road',
    postcode: 'LE1 2LP',
    lat: 52.6387,
    lng: -1.1217,
    phone: '0116 216 1501',
    email: 'qubacentre1@gmail.com',
    description: 'Masjid Quba in the city centre on Brunswick Street.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    rating: 4.5,
    reviewCount: 64,
  }),
  base({
    id: 'l34',
    slug: 'masjid-al-falah-leicester',
    name: 'Masjid al Falah & Islamic Educational Trust',
    address: '3–13 Keythorpe Street',
    postcode: 'LE2 0AL',
    lat: 52.6352,
    lng: -1.1150,
    phone: '0116 251 1833',
    email: 'info@masjidalfalah.org.uk',
    website: 'https://masjidalfalah.org.uk',
    description: 'Masjid al Falah on Keythorpe Street — education trust and community masjid.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah', 'funeral'],
    rating: 4.6,
    reviewCount: 72,
  }),
  base({
    id: 'l35',
    slug: 'masjid-ali-leicester',
    name: 'Masjid Ali',
    address: '42–52 Smith Dorrien Road',
    postcode: 'LE5 4BG',
    lat: 52.6210,
    lng: -1.0773,
    phone: '0116 274 2366',
    website: 'https://masjidali.co.uk',
    description: 'Masjid Ali on Smith Dorrien Road in North Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral', 'nikah'],
    rating: 4.5,
    reviewCount: 55,
  }),
  base({
    id: 'l36',
    slug: 'jamia-masjid-bilal-leicester',
    name: 'Jamia Masjid-e-Bilal',
    address: '80 Evington Valley Road',
    postcode: 'LE5 5LJ',
    lat: 52.6188,
    lng: -1.0915,
    phone: '0116 249 0887',
    website: 'https://bilalmasjid.org',
    description: 'Jamia Masjid-e-Bilal on Evington Valley Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'funeral'],
    rating: 4.5,
    reviewCount: 49,
  }),
  base({
    id: 'l37',
    slug: 'masjid-al-ameen-oadby',
    name: 'Masjid al-Ameen',
    address: 'Sandhurst Street, Oadby',
    postcode: 'LE2 5AR',
    lat: 52.6006,
    lng: -1.0850,
    website: 'https://www.owma.org.uk',
    description: 'Masjid al-Ameen in Oadby serving south Leicester Muslims.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'nikah'],
    rating: 4.4,
    reviewCount: 38,
  }),
  base({
    id: 'l38',
    slug: 'gulzar-e-madina-leicester',
    name: 'Gulzar-e-Madina Mosque',
    address: 'Melbourne Centre, Melbourne Road',
    postcode: 'LE2 0GU',
    lat: 52.6344,
    lng: -1.1138,
    phone: '0116 251 1134',
    email: 'gulzaremadina@hotmail.co.uk',
    website: 'https://gulzaremadinaleicester.co.uk',
    description: 'Gulzar-e-Madina Mosque at the Melbourne Centre on Melbourne Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 42,
  }),
  base({
    id: 'l39',
    slug: 'markaz-quba-leicester',
    name: 'Markaz Quba',
    address: '21 Tichborne Street',
    postcode: 'LE2 0NQ',
    lat: 52.6286,
    lng: -1.1188,
    phone: '0116 319 0220',
    website: 'https://markazquba.org.uk',
    description: 'Markaz Quba on Tichborne Street near the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    rating: 4.5,
    reviewCount: 51,
  }),
  base({
    id: 'l40',
    slug: 'taybah-islamic-centre-leicester',
    name: 'Taybah Islamic Centre',
    address: '362 St Saviours Road',
    postcode: 'LE5 4HJ',
    lat: 52.6390,
    lng: -1.1095,
    phone: '0116 273 8006',
    email: 'info@taybahcentre.org',
    website: 'https://taybahcentre.org',
    description: 'Taybah Islamic Centre on St Saviours Road in Highfields.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club', 'womens-programme'],
    rating: 4.5,
    reviewCount: 46,
  }),
  base({
    id: 'l41',
    slug: 'masjid-baitul-mukarram-leicester',
    name: 'Masjid-e-Baitul Mukarram',
    address: '22–24 St Stephens Road',
    postcode: 'LE2 1DQ',
    lat: 52.6265,
    lng: -1.1205,
    phone: '0116 254 6138',
    description: 'Masjid-e-Baitul Mukarram on St Stephens Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 33,
  }),
  base({
    id: 'l42',
    slug: 'islamic-dawah-academy-leicester',
    name: 'Islamic Dawah Academy',
    address: '120 Melbourne Road',
    postcode: 'LE2 0DS',
    lat: 52.6344,
    lng: -1.1138,
    phone: '0116 262 5440',
    website: 'https://idauk.org',
    description: 'Islamic Dawah Academy on Melbourne Road — major education and dawah centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling', 'youth-club'],
    rating: 4.7,
    reviewCount: 95,
    featured: true,
  }),
  base({
    id: 'l43',
    slug: 'jamia-mosque-jameah-leicester',
    name: 'Jamia Mosque (Jameah Institute)',
    address: 'Evington area',
    postcode: 'LE5 3QJ',
    lat: 52.6215,
    lng: -1.0723,
    phone: '0116 262 1963',
    website: 'https://www.jameah.co.uk',
    description: 'Jamia Mosque and Jameah Institute in Evington — Islamic seminary and masjid.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.6,
    reviewCount: 68,
  }),
  base({
    id: 'l44',
    slug: 'masjid-fatimah-zahrah-leicester',
    name: 'Masjid Fatimah Zahrah (R.A)',
    address: '72–74 Osmaston Road',
    postcode: 'LE5 5JG',
    lat: 52.6255,
    lng: -1.0955,
    description: 'Masjid Fatimah Zahrah on Osmaston Road in Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'womens-programme'],
    rating: 4.4,
    reviewCount: 29,
  }),
  base({
    id: 'l45',
    slug: 'masjid-tabuk-leicester',
    name: 'Masjid Tabuk & Evington Muslim Centre',
    address: '59 Stoughton Drive North',
    postcode: 'LE5 5UD',
    lat: 52.6229,
    lng: -1.1029,
    phone: '0116 273 5529',
    description: 'Masjid Tabuk on Stoughton Drive North in Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 36,
  }),
  base({
    id: 'l46',
    slug: 'masjid-al-huda-leicester',
    name: 'Masjid Al Huda',
    address: '8 Britannia Street',
    postcode: 'LE1 3LE',
    lat: 52.6427,
    lng: -1.1271,
    phone: '0116 251 4807',
    email: 'alhuda8@hotmail.co.uk',
    description: 'Masjid Al Huda on Britannia Street near Belgrave Gate.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 34,
  }),
  base({
    id: 'l47',
    slug: 'masjid-baytul-ilm-leicester',
    name: 'Masjid Baytul Ilm',
    address: 'Spinney Hill Road',
    postcode: 'LE5 3GH',
    lat: 52.6285,
    lng: -1.0950,
    phone: '0116 251 1018',
    email: 'info@baytulilm.org',
    website: 'https://baytulilm.org',
    description: 'Masjid Baytul Ilm on Spinney Hill Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'counselling'],
    rating: 4.5,
    reviewCount: 47,
  }),
  base({
    id: 'l48',
    slug: 'masjid-salahuddin-leicester',
    name: 'Masjid Salahuddin',
    address: '9 Upper George Street',
    postcode: 'LE1 3LQ',
    lat: 52.6365,
    lng: -1.1285,
    phone: '0116 221 0569',
    description: 'Masjid Salahuddin on Upper George Street in the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 28,
  }),
  base({
    id: 'l49',
    slug: 'masjid-ibn-uthaymeen-leicester',
    name: 'Masjid Ibn Uthaymeen',
    address: '24 Madras Road, St Matthews',
    postcode: 'LE1 2LT',
    lat: 52.6395,
    lng: -1.1195,
    phone: '0116 319 1079',
    description: 'Masjid Ibn Uthaymeen on Madras Road in St Matthews.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 31,
  }),
  base({
    id: 'l50',
    slug: 'ukim-leicester-islamic-centre',
    name: 'UKIM Leicester Islamic Centre',
    address: '41 Gwendolen Road',
    postcode: 'LE5 5FL',
    lat: 52.6275,
    lng: -1.1015,
    phone: '0116 273 0043',
    website: 'https://www.ukim.org',
    description: 'UKIM Leicester Islamic Centre on Gwendolen Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    rating: 4.4,
    reviewCount: 40,
  }),
  base({
    id: 'l51',
    slug: 'masjid-noor-ul-islam-leicester',
    name: 'Masjid Noor ul Islam',
    address: 'Linden House, 55 Linden Street',
    postcode: 'LE5 5EE',
    lat: 52.6330,
    lng: -1.1040,
    description: 'Masjid Noor ul Islam on Linden Street in St Matthews.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 27,
  }),
  base({
    id: 'l52',
    slug: 'faizan-e-madina-leicester',
    name: 'Faizan-e-Madina Masjid',
    address: '148 Malabar Road',
    postcode: 'LE1 2LG',
    lat: 52.6405,
    lng: -1.1194,
    phone: '0116 319 4660',
    description: 'Faizan-e-Madina Masjid on Malabar Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 38,
  }),
  base({
    id: 'l53',
    slug: 'masjid-us-sunnah-welford-road',
    name: 'Masjid us-Sunnah',
    address: '176 Welford Road, Clarendon Park',
    postcode: 'LE2 6BD',
    lat: 52.6145,
    lng: -1.1285,
    phone: '0116 298 4781',
    website: 'https://www.masjid-us-sunnah.com',
    description: 'Masjid us-Sunnah on Welford Road in Clarendon Park (distinct from Knighton CEC).',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.5,
    reviewCount: 44,
  }),
  base({
    id: 'l54',
    slug: 'majles-dawat-ul-haq-leicester',
    name: 'Majles-e-Dawat Ul Haq',
    address: '126–128 Earl Howe Street',
    postcode: 'LE2 0DG',
    lat: 52.6325,
    lng: -1.1085,
    phone: '0116 255 9847',
    website: 'https://www.majlisedawatulhaq.org.uk',
    description: 'Majles-e-Dawat Ul Haq on Earl Howe Street in Highfields.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 35,
  }),
  base({
    id: 'l55',
    slug: 'dar-us-salam-leicester',
    name: 'Dar-us-Salam Mosque',
    address: '55–57 Upper Tichborne Street',
    postcode: 'LE2 1GL',
    lat: 52.6295,
    lng: -1.1175,
    phone: '0116 254 3887',
    description: 'Dar-us-Salam Mosque on Upper Tichborne Street.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 30,
  }),
  base({
    id: 'l56',
    slug: 'masjid-ar-rahman-leicester',
    name: 'Masjid Ar-Rahman',
    address: '71 Guthlaxton Road',
    postcode: 'LE2 0SF',
    lat: 52.6270,
    lng: -1.1120,
    description: 'Masjid Ar-Rahman on Guthlaxton Road in Highfields.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 26,
  }),
  base({
    id: 'l57',
    slug: 'masjid-fida-leicester',
    name: 'Masjid Fida',
    address: '33 Rowsley Street & 9 Osmaston Road',
    postcode: 'LE5 5JN',
    lat: 52.6240,
    lng: -1.0965,
    phone: '0116 225 3532',
    website: 'https://fidaleicester.com',
    description: 'Masjid Fida on Rowsley Street and Osmaston Road in Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 32,
  }),
  base({
    id: 'l58',
    slug: 'masjid-al-khaleel-leicester',
    name: 'Masjid Al Khaleel',
    address: '49 Donnington Street',
    postcode: 'LE2 0DE',
    lat: 52.6310,
    lng: -1.1145,
    phone: '0116 255 1524',
    website: 'https://www.majlisiquran.com',
    description: 'Masjid Al Khaleel on Donnington Street in Highfields.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.4,
    reviewCount: 29,
  }),
  base({
    id: 'l59',
    slug: 'muslim-community-college-leicester',
    name: 'Muslim Community College',
    address: '372 East Park Road',
    postcode: 'LE5 5AY',
    lat: 52.6318,
    lng: -1.1055,
    phone: '0116 273 4446',
    website: 'https://muslimcommunitycollege.org',
    description: 'Muslim Community College masjid and education centre on East Park Road.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    rating: 4.4,
    reviewCount: 37,
  }),
  base({
    id: 'l60',
    slug: 'hamidiye-camii-leicester',
    name: 'Hamidiye Camii (Süleymaniye Mosque)',
    address: '16 Great Central Street',
    postcode: 'LE1 4JT',
    lat: 52.6335,
    lng: -1.1355,
    phone: '0116 262 4465',
    website: 'https://www.suleymaniye.org',
    description: 'Hamidiye Camii Turkish mosque on Great Central Street near Leicester station.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'womens-facilities'],
    rating: 4.5,
    reviewCount: 55,
  }),
  base({
    id: 'l61',
    slug: 'northfields-education-centre-leicester',
    name: 'Northfields Education Centre',
    address: '8 Essex Road',
    postcode: 'LE4 9EE',
    lat: 52.6381,
    lng: -1.0972,
    phone: '07553 920777',
    description: 'Northfields Education Centre masjid on Essex Road in north Leicester.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 24,
  }),
  base({
    id: 'l62',
    slug: 'hafsah-islamic-centre-leicester',
    name: 'Hafsah Islamic Centre',
    address: '6 Sylvan Avenue, North Evington',
    postcode: 'LE5 3SN',
    lat: 52.6210,
    lng: -1.0773,
    phone: '0116 216 6234',
    description: 'Hafsah Islamic Centre on Sylvan Avenue.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'womens-programme'],
    rating: 4.3,
    reviewCount: 28,
  }),
  base({
    id: 'l63',
    slug: 'beaumont-leys-muslims',
    name: 'Beaumont Leys Muslims',
    address: 'Home Farm Court, Home Farm Close',
    postcode: 'LE4 0SU',
    lat: 52.6680,
    lng: -1.1550,
    email: 'info@blmuslims.org',
    website: 'https://blmuslims.org',
    description: 'Beaumont Leys Muslims community masjid in north-west Leicester.',
    jumuahTimes: ['13:30'],
    services: ['madrasah', 'youth-club'],
    rating: 4.4,
    reviewCount: 33,
  }),
  base({
    id: 'l64',
    slug: 'masjid-an-noor-berners-street',
    name: 'Masjid An-Noor (Berners Street)',
    address: '146 Berners Street, Spinney Hill',
    postcode: 'LE2 0FU',
    lat: 52.6298,
    lng: -1.1005,
    phone: '0116 262 2640',
    description: 'Masjid An-Noor on Berners Street in Spinney Hill.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 22,
  }),
  base({
    id: 'l65',
    slug: 'masjidul-abrar-leicester',
    name: 'Masjidul Abrar',
    address: '126a Ross Walk, Belgrave',
    postcode: 'LE4 5HH',
    lat: 52.6620,
    lng: -1.1180,
    description: 'Masjidul Abrar on Ross Walk in Belgrave.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 25,
  }),
  base({
    id: 'l66',
    slug: 'madressah-rahimiyah-leicester',
    name: 'Madressah-e-Rahimiyah',
    address: '127 Mere Road',
    postcode: 'LE5 5GQ',
    lat: 52.6260,
    lng: -1.0880,
    phone: '0116 251 1120',
    description: 'Madressah-e-Rahimiyah on Mere Road in Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 24,
  }),
  base({
    id: 'l67',
    slug: 'jamia-sufiya-leicester',
    name: 'Jamia Sufiya',
    address: '44 Highfield Street',
    postcode: 'LE2 1AD',
    lat: 52.6255,
    lng: -1.1255,
    phone: '0116 255 3926',
    website: 'https://jamiasufiya.co.uk',
    description: 'Jamia Sufiya on Highfield Street near the city centre.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.3,
    reviewCount: 26,
  }),
  base({
    id: 'l68',
    slug: 'tajdaar-e-madina-leicester',
    name: 'Tajdaar e Madina',
    address: '1a Garendon Street, Maidstone Road',
    postcode: 'LE2 0AH',
    lat: 52.6360,
    lng: -1.1169,
    phone: '07713 164475',
    website: 'https://www.temadina.co.uk',
    description: 'Tajdaar e Madina on Garendon Street.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.2,
    reviewCount: 20,
  }),
  base({
    id: 'l69',
    slug: 'darus-salam-evington-leicester',
    name: 'Darus Salam Mosque (Evington)',
    address: '82 Kedleston Road, Evington',
    postcode: 'LE5 5HW',
    lat: 52.6165,
    lng: -1.0855,
    description: 'Darus Salam Mosque on Kedleston Road in Evington.',
    jumuahTimes: ['13:30'],
    services: ['madrasah'],
    rating: 4.2,
    reviewCount: 18,
  }),
]
